language: rust

rust:
  - stable
  - beta
  - nightly

sudo: false
cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
      - cargo build --verbose --all
      - cargo test --verbose --all
