[package]
authors = ["Peltoche <dev@halium.fr>"]
build = "build.rs"
categories = ["command-line-utilities"]
description = "A ls command with a lot of pretty colors."
homepage = "https://github.com/Peltoche/lsd"
keywords = ["ls"]
license-file = "./LICENSE"
name = "lsd"
readme = "./README.md"
repository = "https://github.com/Peltoche/lsd"
version = "0.6.4-pre"

[[bin]]
name = "lsd"
path = "src/main.rs"

[build-dependencies]
clap = "2.32.0"
version_check = "0.1.3"

[dependencies]
ansi_term = "0.11.0"
lazy_static = "1.2.0"
libc = "0.2.44"
term_grid = "0.1.7"
terminal_size = "0.1.8"
time = "0.1.40"
users = "0.8.0"

[dependencies.clap]
version = "2.32.0"
features = ["suggestions", "color", "wrap_help"]
